name: Deploy CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          mkdir -p /home/runner/.aws
          echo "[default]
          aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > /home/runner/.aws/credentials

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation create-stack --stack-name MyStackName \
          --template-body file://my-template.yaml \
          --region us-east-1 # Replace with your desired AWS region

      - name: Wait for Stack to Complete
        run: |
          aws cloudformation wait stack-create-complete --stack-name MyStackName \
          --region us-east-1 # Replace with your desired AWS region

      - name: Display Stack Outputs
        run: |
          aws cloudformation describe-stacks --stack-name MyStackName \
          --query 'Stacks[0].Outputs' \
          --output table \
          --region us-east-1 # Replace with your desired AWS region

    #capabilities: CAPABILITY_NAMED_IAM
